/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { workflowsStepsRetrieve } from "../funcs/workflowsStepsRetrieve.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Steps extends ClientSDK {
  /**
   * Get workflow step data
   *
   * @remarks
   * Retrieves data for a specific step in a workflow
   */
  async retrieve(
    workflowId: string,
    stepId: string,
    idempotencyKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<operations.WorkflowControllerGetWorkflowStepDataResponse> {
    return unwrapAsync(workflowsStepsRetrieve(
      this,
      workflowId,
      stepId,
      idempotencyKey,
      options,
    ));
  }
}
